import { products } from "../data/nj-gas-station.js";
import { peso, number, escapeHtml, localDate } from "./format.js";
import { capacity, activeBuyingPrice } from "./operations.js";

export function reportInputs(state) {
  const disabled = ["Owner", "Station Manager"].includes(state.role) ? "" : "disabled";
  const options = products.map((p) => `<option value="${p.id}">${p.name}</option>`).join("");
  const months = [...new Set([...state.monthlyExpenses.map((r) => r.month), ...state.closeouts.filter((r) => r.workflow === "approved" && r.fifoAllocations).map((r) => r.date.slice(0,7))])].sort().reverse();
  return `<section class="panel form-panel"><h2>Monthly inputs and operating controls</h2><p>Electricity and manpower are monthly amounts, deducted once in the monthly summary—not on each daily closeout. Corrections retain earlier expense revisions.</p>
  <form data-monthly-form="expenses" class="cost-grid"><label>Expense month<input name="month" type="month" value="${localDate().slice(0,7)}" required /></label><label>Monthly electricity (₱)<input name="electricity" type="number" min="0" step="0.01" required /></label><label>Monthly manpower (₱)<input name="manpower" type="number" min="0" step="0.01" required /></label><label>Bill / payroll reference and reason<input name="reason" required maxlength="500" /></label><button class="primary" ${disabled}>Save monthly expenses</button></form>
  <h3>Monthly calibration / testing evidence</h3><p>Enter positive test liters manually. Returned test fuel is deducted once from meter movement on its dated closeout: 100 L movement − 30 L returned testing = 70 L sold and 70 L net stock consumed. Physical totalizers still increase. Non-returned or unconfirmed tests require separate review.</p>
  <form data-monthly-form="calibration" class="cost-grid"><label>Test month<input name="month" type="month" value="${localDate().slice(0,7)}" required /></label><label>Actual test date<input name="testDate" type="date" required /></label><label>Test product<select name="product">${options}</select></label><label>Test liters<input name="liters" type="number" min="0.01" step="0.01" required /></label><label>Fuel after testing<select name="returnStatus"><option value="unconfirmed">Not confirmed</option><option value="returned">Returned to same tank</option><option value="not-returned">Not returned</option></select></label><label>Test document / closeout reference<input name="reference" maxlength="200" /></label><label>Test explanation<input name="reason" required maxlength="500" /></label><button class="primary" ${disabled}>Record test for review</button></form>
  ${state.monthlyTests.map((r) => `<p>${escapeHtml(r.month)} · ${escapeHtml(r.testDate || "Date unassigned")} · ${escapeHtml(r.product)} · ${number(r.liters)} L · ${escapeHtml(r.returnStatus)} · ${escapeHtml(r.status)} · ${escapeHtml(r.reason)}</p>${!r.voided && !r.closeoutId && !disabled ? `<form data-void-test="${escapeHtml(r.id)}"><label>Void reason<input name="reason" required maxlength="500" /></label><button class="secondary">Void unposted test</button></form>` : ""}`).join("")}
  <h3>Working capacity — owner only</h3><p>${products.map((p) => `${p.name}: ${number(capacity(state,p.id))} L`).join(" · ")}</p>
  ${state.role === "Owner" ? `<form id="capacity-form" class="cost-grid"><label>Tank product<select name="product">${options}</select></label><label>Working capacity (L)<input name="liters" type="number" min="0.01" step="0.01" required /></label><label>Capacity change reason<input name="reason" required maxlength="500" /></label><button class="primary">Save working capacity</button></form>` : "<p>Only the Owner role can edit working capacity.</p>"}
  <h3>FIFO buying-cost batches</h3><p>Old stock retains its recorded buying cost until consumed. A sale spanning batches uses both costs. Opening carry-in costs are provisional until reconciled with the owner.</p>
  ${products.map((p) => `<p><strong>${p.name}: next stock cost ${peso(activeBuyingPrice(state,p.id))}/L</strong><br>${(state.inventoryLots?.[p.id] || []).filter((l) => l.remaining > 0).map((l) => `${number(l.remaining)} L × ${peso(l.unitCost)} · ${escapeHtml(l.basis)}`).join("<br>")}</p>`).join("")}
  <h3>Monthly contribution after overhead</h3><p>Approved FIFO local closeouts only; historical workbook/legacy profit is excluded to avoid double-counting previously allocated costs. Incomplete months are not full-month profit.</p>
  ${months.map((month) => { const rows = state.closeouts.filter((r) => r.workflow === "approved" && r.fifoAllocations && r.date.startsWith(month)); const expenses = state.monthlyExpenses.filter((r) => r.month === month).at(-1); const contribution = rows.reduce((sum,r) => sum+r.profit,0); return `<p><strong>${month}</strong> · ${rows.length} approved day(s) · Contribution ${peso(contribution)} · Electricity ${expenses ? peso(expenses.electricity) : "Not entered"} · Manpower ${expenses ? peso(expenses.manpower) : "Not entered"} · After overhead ${expenses ? peso(contribution-expenses.electricity-expenses.manpower) : "Incomplete"}${expenses ? ` · expense revision ${expenses.revision}` : ""}</p>`; }).join("") || "<p>No monthly inputs yet.</p>"}</section>`;
}
