-- Run against the isolated FDG project as postgres. All synthetic records roll back.
-- This exercises real database permissions/RPCs, not PayMongo or real email delivery.
begin;
do $$
declare
 u uuid:=gen_random_uuid(); other_user uuid:=gen_random_uuid(); sess uuid:=gen_random_uuid(); other_sess uuid:=gen_random_uuid();
 s public.fdg_billing_subscriptions; repeated public.fdg_billing_subscriptions;
 i public.fdg_billing_invoices; repeated_i public.fdg_billing_invoices; claim jsonb; again jsonb;
 denied boolean; n integer; result text; anchor timestamptz:='2026-01-31 12:00:00+00';
begin
 insert into auth.users(id,email,email_confirmed_at) values(u,'billing-test-a-'||u||'@example.invalid',now()),(other_user,'billing-test-b-'||other_user||'@example.invalid',now());
 insert into auth.sessions(id,user_id,created_at,updated_at) values(sess,u,now(),now()),(other_sess,other_user,now(),now());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','session_id',sess)::text,true);
 set local role authenticated;
 s:=public.fdg_test_start_subscription(' Test branch ');
 repeated:=public.fdg_test_start_subscription('test BRANCH');
 if s.id<>repeated.id or s.monthly_centavos<>50000 or s.livemode or s.trial_ends_at-s.trial_started_at<>interval '7 days' then raise exception 'FAIL trial/price/idempotency'; end if;
 denied:=false;
 begin perform public.fdg_test_issue_invoice(s.id); exception when others then if sqlerrm='No invoice due yet' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL early invoice'; end if;
 denied:=false;
 begin update public.fdg_billing_subscriptions set monthly_centavos=1 where id=s.id; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL client write grant'; end if;
 denied:=false;
 begin perform public.fdg_test_claim_checkout(gen_random_uuid(),u); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL client claim execute'; end if;
 denied:=false;
 begin perform public.fdg_test_settle_invoice(gen_random_uuid(),gen_random_uuid(),'cs_test','pay_test',50000,'PHP',repeat('a',64)); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL client settlement execute'; end if;
 reset role;
 update public.fdg_billing_subscriptions set trial_started_at=anchor-interval '7 days',trial_ends_at=anchor where id=s.id;
 set local role authenticated;
 i:=public.fdg_test_issue_invoice(s.id);repeated_i:=public.fdg_test_issue_invoice(s.id);
 if i.id<>repeated_i.id or i.amount_centavos<>50000 or i.period_end<>'2026-02-28 12:00:00+00'::timestamptz then raise exception 'FAIL monthly invoice/anchor/idempotency'; end if;
 reset role;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_user,'role','authenticated','session_id',other_sess)::text,true);
 set local role authenticated;
 select count(*) into n from public.fdg_billing_invoices where id=i.id;
 if n<>0 then raise exception 'FAIL invoice isolation'; end if;
 select count(*) into n from public.fdg_billing_subscriptions where id=s.id;
 if n<>0 then raise exception 'FAIL subscription isolation'; end if;
 denied:=false;
 begin perform public.fdg_test_issue_invoice(s.id); exception when others then if sqlerrm='Subscription unavailable' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL cross-owner RPC'; end if;
 reset role;
 set local role service_role;
 denied:=false;
 begin perform public.fdg_test_claim_checkout(i.id,other_user); exception when others then if sqlerrm='Invoice unavailable' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL checkout owner'; end if;
 claim:=public.fdg_test_claim_checkout(i.id,u);again:=public.fdg_test_claim_checkout(i.id,u);
 if not (claim->>'fresh')::boolean or (again->>'fresh')::boolean or claim->'attempt'->>'id'<>again->'attempt'->>'id' then raise exception 'FAIL checkout claim idempotency'; end if;
 perform public.fdg_test_save_checkout((claim->'attempt'->>'id')::uuid,'cs_databasefixture','https://checkout.paymongo.com/databasefixture');
 denied:=false;
 begin perform public.fdg_test_settle_invoice((claim->'attempt'->>'id')::uuid,i.id,'cs_databasefixture','pay_databasefixture',1,'PHP',repeat('a',64)); exception when others then if sqlerrm='Payment mismatch' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL wrong amount accepted'; end if;
 denied:=false;
 begin perform public.fdg_test_settle_invoice((claim->'attempt'->>'id')::uuid,i.id,'cs_other','pay_databasefixture',50000,'PHP',repeat('a',64)); exception when others then if sqlerrm='Checkout mismatch' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL wrong checkout accepted'; end if;
 result:=public.fdg_test_settle_invoice((claim->'attempt'->>'id')::uuid,i.id,'cs_databasefixture','pay_databasefixture',50000,'PHP',repeat('a',64));
 if result<>'paid' then raise exception 'FAIL settlement'; end if;
 result:=public.fdg_test_settle_invoice((claim->'attempt'->>'id')::uuid,i.id,'cs_databasefixture','pay_databasefixture',50000,'PHP',repeat('b',64));
 if result<>'duplicate' then raise exception 'FAIL duplicate receipt'; end if;
 reset role;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','session_id',sess)::text,true);
 set local role authenticated;
 i:=public.fdg_test_issue_invoice(s.id);
 if i.period_start<>'2026-02-28 12:00:00+00'::timestamptz or i.period_end<>'2026-03-31 12:00:00+00'::timestamptz then raise exception 'FAIL month-end drift'; end if;
 perform public.fdg_test_stop_renewals(s.id);
 select * into repeated from public.fdg_billing_subscriptions where id=s.id;
 if repeated.renewals_enabled or repeated.renewals_stopped_at is null then raise exception 'FAIL stop renewals audit'; end if;
 repeated_i:=public.fdg_test_issue_invoice(s.id);
 if repeated_i.id<>i.id then raise exception 'FAIL outstanding invoice preservation'; end if;
 reset role;
 update auth.sessions set created_at=now()-interval '13 hours' where id=sess;
 set local role authenticated;
 select count(*) into n from public.fdg_billing_invoices where user_id=u;
 if n<>0 then raise exception 'FAIL expired session read'; end if;
 denied:=false;
 begin perform public.fdg_test_start_subscription('expired'); exception when others then if sqlerrm='Sign in again' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'FAIL expired session write'; end if;
 reset role;
 set local role anon;
 denied:=false;
 begin perform public.fdg_test_start_subscription('anonymous'); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'FAIL anonymous RPC'; end if;
 reset role;
end $$;
select 'PASS: real FDG billing database permission, trial, ownership, calendar, settlement and replay assertions; all fixtures rolled back' as result;
rollback;
