import assert from "node:assert/strict";
import { loadState, allReportRows, saveState } from "../src/store.js";
import { attentionIssues, attentionCenter, attentionSummary, attentionLabel, reviewIssue } from "../src/attention.js";
import { addUtilityRate, reviewUtilityRate } from "../src/utility-rates.js";
globalThis.localStorage={ getItem:()=>null, setItem:()=>{} };
const state=loadState();
const original=JSON.stringify(allReportRows(state));
assert.equal(attentionIssues(state).length,3);
assert.equal(attentionLabel(state),"2 source reviews · 1 rate setup");
assert.match(attentionCenter(state),/details class="attention-issue/);
assert.throws(()=>reviewIssue(state,{issueId:"workbook-july2025",status:"Resolved",reason:"fixed"}),/evidence/);
reviewIssue(state,{issueId:"workbook-july2025",status:"Under Review",reason:"locating source",evidence:"July workbook"});
reviewIssue(state,{issueId:"workbook-july2025",status:"Resolved",reason:"review complete",evidence:"review record"});
assert.equal(state.issueReviews.length,2);
assert.equal(attentionSummary(state).active.length,2);
assert.equal(attentionSummary(state).completed.length,1);
assert.equal(attentionLabel(state),"1 source review · 1 rate setup");
assert.match(attentionCenter(state),/Completed review history · 1/);
assert.equal(JSON.stringify(allReportRows(state)),original);
const input={utility:"electricity",rate:"12.56",from:"2025-01-01",to:"2025-01-31",source:"Test bill fixture only"};
assert.throws(()=>addUtilityRate(state,{...input,from:"2025-02-30"}),/dates/);
assert.throws(()=>addUtilityRate(state,{...input,rate:""}),/rate/);
const rate=addUtilityRate(state,input); assert.equal(rate.status,"pending");
reviewUtilityRate(state,rate.id,"approved","fixture checked");
const duplicate=addUtilityRate(state,input);
assert.throws(()=>reviewUtilityRate(state,duplicate.id,"approved","duplicate"),/overlapping/);
reviewUtilityRate(state,duplicate.id,"rejected","duplicate period");
assert.throws(()=>reviewUtilityRate(state,rate.id,"rejected","overwrite"),/pending/);
const next=addUtilityRate(state,{...input,from:"2025-02-01",to:"2025-02-28"});
reviewUtilityRate(state,next.id,"approved","next period");
assert.equal(state.monthlyExpenses.length,0);
const correction=addUtilityRate(state,{...input,rate:13,supersedes:rate.id});
reviewUtilityRate(state,correction.id,"approved","corrected bill");
assert.equal(rate.rate,12.56); assert.equal(rate.status,"superseded");
assert.equal(rate.supersededBy,correction.id);
assert.throws(()=>addUtilityRate(state,{...input,supersedes:rate.id}),/correction/);
state.role="Attendant";
assert.throws(()=>addUtilityRate(state,input),/role|manager/i);
assert.throws(()=>reviewIssue(state,{issueId:"utility-rate-basis",status:"Open",reason:"x",evidence:"x"}),/role|manager/i);
state.role="Owner"; saveState(state);
globalThis.localStorage.setItem=()=>{throw Error("quota");};
reviewIssue(state,{issueId:"utility-rate-basis",status:"Under Review",reason:"x",evidence:"x"});
assert.throws(()=>saveState(state),/Not saved/);
assert.equal(state.issueReviews.length,2);
console.log("PASS issue audit/exclusion/role checks; rate dates, overlap, immutable decisions; save rollback");
