import assert from 'node:assert/strict';
import { loadState, saveState, latestTotalizerRecord } from '../src/store.js';
import { commissionMeters, meterEntries } from '../src/meters.js';
import { submitCloseout, reviewCloseout } from '../src/closeouts.js';
import { saveMonthlyRecord } from '../src/operations.js';
let raw = null;
globalThis.localStorage = { getItem: () => raw, setItem: (_, value) => { raw = value; } };
const state = loadState();
const setup = { date: latestTotalizerRecord(state).date, reference:'Verified test fixture only', sets:[{id:'D1',forecourt:'North',products:[{product:'regular',opening:1000},{product:'premium',opening:5000}]},{id:'D2',forecourt:'South',products:[{product:'regular',opening:2000}]}] };
const original = structuredClone(state);
state.role='Attendant'; assert.throws(()=>commissionMeters(state,setup),/Owner/); state.role='Owner';
assert.throws(()=>commissionMeters(state,{...setup,date:'2026-09-21'}),/latest accepted/);
assert.throws(()=>commissionMeters(state,{...setup,sets:[setup.sets[0],setup.sets[0]]}),/unique/);
assert.throws(()=>commissionMeters(state,{...setup,sets:[{...setup.sets[0],products:[]}]}),/1–3/);
commissionMeters(state,setup); saveState(state);
assert.deepEqual(state.tanks,original.tanks);
assert.deepEqual(state.closeouts,original.closeouts);
assert.equal(meterEntries(loadState()).length,3);
saveMonthlyRecord(state,{kind:'calibration',month:'2025-04',testDate:'2025-04-30',testTime:'09:00',pump:'D1',tank:'T1',product:'regular',liters:30,returnStatus:'returned',reference:'CAL',reason:'Returned'},'2026-09-21');
const input={date:'2025-04-30',meters:{'D1--regular':{closing:1100,test:30},'D1--premium':{closing:5020,test:0},'D2--regular':{closing:2040,test:0}},otherCost:0,cashCollected:0};
assert.throws(()=>submitCloseout(state,{...input,meters:{}},'2026-09-21'),/every/);
assert.throws(()=>submitCloseout(state,{...input,meters:{...input.meters,'D2--regular':{closing:1999,test:0}}},'2026-09-21'),/below/);
assert.throws(()=>submitCloseout(state,{...input,meters:{...input.meters,'D1--regular':{closing:1100,test:0},'D2--regular':{closing:2040,test:30}}},'2026-09-21'),/calibration/);
const row=submitCloseout(state,input,'2026-09-21');
assert.equal(row.regularLiters,110); assert.equal(row.premiumLiters,20); assert.equal(row.dieselLiters,0);
assert.equal(meterEntries(state)[0].opening,1000); assert.deepEqual(state.tanks,original.tanks);
reviewCloseout(state,row.id,'approved','Checked individual meters');
assert.equal(meterEntries(state)[0].opening,1100); assert.equal(state.tanks.regular,original.tanks.regular-110);
const correction=submitCloseout(state,{...input,replaces:row.id,reason:'Correct D2',meters:{...input.meters,'D2--regular':{closing:2050,test:0}}},'2026-09-21');
assert.equal(correction.meterReadings['D1--regular'].opening,1000);
reviewCloseout(state,correction.id,'approved','Checked correction');
assert.equal(state.tanks.regular,original.tanks.regular-120);
assert.equal(meterEntries(state).find(m=>m.id==='D2--regular').opening,2050);
assert.throws(()=>commissionMeters(state,setup),/locked/);
saveState(state); const restored=loadState(); assert.deepEqual(restored.closeouts,state.closeouts);
const next=submitCloseout(restored,{...input,date:'2025-05-01',meters:Object.fromEntries(meterEntries(restored).map(m=>[m.id,{closing:m.opening+1,test:0}]))},'2026-09-21');
reviewCloseout(restored,next.id,'rejected','Photo not clear'); assert.equal(meterEntries(restored)[0].opening,1100);
console.log('PASS independent meters, 1–3 products, commissioning evidence/roles, approval-only carry, scoped calibration, correction delta, reload and rejected carry');
