import assert from "node:assert/strict";
import { loadState, latestTotalizerRecord } from "../src/store.js";
import { consumeLots, addDeliveryLot, saveCapacity, capacity, saveMonthlyRecord, voidCalibration, registeredTests } from "../src/operations.js";
import { submitCloseout, reviewCloseout } from "../src/closeouts.js";
globalThis.localStorage = { getItem: () => null };
const lots=[{id:"old",date:"2025-04-29",remaining:100,unitCost:50},{id:"new",date:"2025-04-30",remaining:500,unitCost:60}];
assert.equal(consumeLots(lots,70,"2025-04-30").cost,3500);
assert.equal(lots[0].remaining,30);
assert.equal(consumeLots(lots,50,"2025-04-30").cost,2700); // 30 old + 20 new
assert.equal(lots[1].remaining,480);
assert.throws(()=>consumeLots(structuredClone(lots),481,"2025-04-30"),/Not enough/);
const state=loadState();
state.inventoryLots.regular=[{id:"opening",date:"2025-04-29",remaining:100,unitCost:50,basis:"Test opening"}]; state.tanks.regular=100;
addDeliveryLot(state,{id:"delivery",date:"2025-04-30",product:"regular",liters:500,unitCost:60});state.tanks.regular+=500;
const opening=latestTotalizerRecord(state).values;
const test={kind:"calibration",month:"2025-04",testDate:"2025-04-30",product:"regular",liters:30,returnStatus:"returned",reference:"CAL-1",reason:"Returned to same tank"};
saveMonthlyRecord(state,test,"2026-09-17");
assert.throws(()=>saveMonthlyRecord(state,test,"2026-09-17"),/already recorded/);
const input={date:"2025-04-30",closing:{...opening,regular:opening.regular+100},tests:{regular:30,premium:0,diesel:0},electricity:999,manpower:999,otherCost:0,cashCollected:70*state.prices.regular.sellingPrice};
assert.throws(()=>submitCloseout(state,{...input,tests:{regular:60,premium:0,diesel:0}},"2026-09-17"),/once/);
const row=submitCloseout(state,input,"2026-09-17");
assert.equal(row.regularLiters,70);assert.equal(row.costs.electricity,0);assert.equal(row.costs.manpower,0);
assert.equal(state.tanks.regular,600);
reviewCloseout(state,row.id,"approved","Checked 100-30=70");
assert.equal(state.tanks.regular,530);assert.equal(row.costOfFuel,3500);assert.equal(state.inventoryLots.regular[0].remaining,30);
assert.equal(row.profit,row.sales-3500);
assert.throws(()=>voidCalibration(state,state.monthlyTests[0].id,"edit"),/submitted/);
const correction=submitCloseout(state,{...input,closing:{...opening,regular:opening.regular+150},replaces:row.id,reason:"Corrected final reading"},"2026-09-17");
reviewCloseout(state,correction.id,"approved","Reviewed FIFO split");
assert.equal(correction.regularLiters,120);assert.equal(correction.costOfFuel,6200);assert.equal(state.tanks.regular,480);
saveMonthlyRecord(state,{kind:"expenses",month:"2025-04",electricity:1000,manpower:2000,reason:"Bills"},"2026-09-17");
saveMonthlyRecord(state,{kind:"expenses",month:"2025-04",electricity:1100,manpower:2100,reason:"Corrected bills"},"2026-09-17");
assert.equal(state.monthlyExpenses.length,2);assert.equal(state.monthlyExpenses.at(-1).revision,2);
state.role="Station Manager";assert.throws(()=>saveCapacity(state,{product:"regular",liters:1000,reason:"Tank plate"}),/Owner/);
state.role="Owner";assert.throws(()=>saveCapacity(state,{product:"regular",liters:479,reason:"Too small"}),/below/);
saveCapacity(state,{product:"regular",liters:1000,reason:"Verified working limit"});assert.equal(capacity(state,"regular"),1000);
saveMonthlyRecord(state,{...test,month:"2025-05",testDate:"2025-05-01",reference:"CAL-2"},"2026-09-17");
voidCalibration(state,state.monthlyTests.at(-1).id,"Duplicate paper entry");assert.equal(registeredTests(state,"2025-05-01","regular").length,0);
console.log("PASS FIFO 100+500, batch-crossing costs, correction restoration, returned 100-30=70, duplicate calibration, monthly revisions, owner-only capacity");
