import assert from "node:assert/strict";
import vm from "node:vm";
import fs from "node:fs";
import { loadState, saveState, latestTotalizerRecord, allReportRows } from "../src/store.js";
import { submitCloseout, reviewCloseout } from "../src/closeouts.js";
import { totalizerCandidates } from "../src/ocr.js";
let raw = null; let fail = false;
globalThis.localStorage = { getItem: () => raw, setItem: (_, v) => { if (fail) throw new Error("quota exceeded"); raw=v; }, removeItem: () => { raw=null; } };
const state=loadState(); saveState(state);
const opening=latestTotalizerRecord(state).values;
const input=(date,liters=10) => ({date, closing:Object.fromEntries(Object.entries(opening).map(([k,v])=>[k,v+liters])),tests:{regular:0,premium:0,diesel:0},electricity:0,manpower:0,otherCost:0,cashCollected:1917.5});
for(const date of ["2024-01-01","2025-04-29","2026-02-30","2027-01-01","2025-05-02"]) assert.throws(()=>submitCloseout(state,input(date),"2026-09-17"));
const before=structuredClone(state.tanks);
const pending=submitCloseout(state,input("2025-04-30"),"2026-09-17");
assert.deepEqual(state.tanks,before); assert.equal(allReportRows(state).length,4);
assert.throws(()=>submitCloseout(state,input("2026-09-17"),"2026-09-17"),/pending/);
state.role="Attendant"; assert.throws(()=>reviewCloseout(state,pending.id,"approved","checked"),/role/); state.role="Owner";
reviewCloseout(state,pending.id,"approved","Compared readings and cash"); saveState(state);
assert.equal(state.tanks.regular,before.regular-10); assert.equal(allReportRows(state).length,5);
assert.throws(()=>reviewCloseout(state,pending.id,"approved","retry"),/no longer pending/);
const correction=submitCloseout(state,{...input("2025-04-30",12),replaces:pending.id,reason:"Transcription correction"},"2026-09-17");
assert.equal(state.tanks.regular,before.regular-10);
reviewCloseout(state,correction.id,"approved","Meter checked"); saveState(state);
assert.equal(pending.workflow,"superseded"); assert.equal(state.tanks.regular,before.regular-12); assert.equal(allReportRows(state).length,5);
const next=input("2025-05-01",22); const rejected=submitCloseout(state,next,"2026-09-17"); reviewCloseout(state,rejected.id,"rejected","Wrong reading"); saveState(state);
assert.equal(state.tanks.regular,before.regular-12);
const resubmitted=submitCloseout(state,{...next,replaces:rejected.id,reason:"Confirmed all meters"},"2026-09-17");
saveState(state);
const pendingSaved=raw;
reviewCloseout(state,resubmitted.id,"approved","Checked all products");
fail=true; assert.throws(()=>saveState(state),/Not saved/); fail=false;
assert.equal(raw,pendingSaved); assert.equal(state.closeouts.at(-1).workflow,"pending");
assert.equal(state.tanks.regular,before.regular-12);
reviewCloseout(state,resubmitted.id,"rejected","Controlled test rollback"); saveState(state);
const durable=raw; state.tanks.regular=1; fail=true; assert.throws(()=>saveState(state),/Not saved/); fail=false;
assert.equal(raw,durable); assert.equal(state.tanks.regular,before.regular-12);
raw=durable+" "; assert.throws(()=>saveState(state),/another tab/); raw=durable;
assert.equal(latestTotalizerRecord({closeouts:[{date:"2024-01-01",closingTotalizers:{regular:1}}]}).date,"2025-04-29");
assert.deepEqual(totalizerCandidates([{rawValue:"68,212.44"},{rawValue:"68,212.44"}],68202.44),[68212.44]);
assert.deepEqual(totalizerCandidates([{rawValue:"68,212.44 78,212.44"}],68202.44),[68212.44,78212.44]);
assert.deepEqual(totalizerCandidates([{rawValue:"unreadable 12"}],68202.44),[]);
raw="{broken";
const corruptStore=await import("../src/store.js?corrupt-test");
const protectedState=corruptStore.loadState();
assert.throws(()=>corruptStore.saveState(protectedState),/Not saved/);
assert.throws(()=>corruptStore.resetDemo(),/protected/); assert.equal(raw,"{broken");
for(const [file,prefix] of [["../sw.js","fdg-fuel-station-"],["../../sw.js","fdg-business-platform-"]]) {
  let activate; const deleted=[];
  const context={self:{addEventListener:(name,fn)=>{if(name==="activate")activate=fn;},clients:{claim:async()=>{}}},caches:{keys:async()=>["fdg-fuel-station-v1","fdg-business-platform-v1","other-app-v1"],delete:async(key)=>deleted.push(key)}};
  vm.runInNewContext(fs.readFileSync(new URL(file,import.meta.url),"utf8"),context);
  let task; activate({waitUntil:(p)=>task=p}); await task;
  assert.deepEqual(deleted,[prefix+"v1"]);
  const script=fs.readFileSync(new URL(file,import.meta.url),"utf8");
  assert.equal(script.includes("caches.match("),false,"reads must be scoped to the module cache");
  const shell=script.match(/const SHELL = \[([\s\S]*?)\];/)[1];
  for(const match of shell.matchAll(/"(\.\/[^\"]*)"/g)) assert.ok(fs.existsSync(new URL(match[1],new URL(file,import.meta.url))),`Missing offline shell: ${match[1]}`);
}
console.log("PASS: dates, pending approval, revision delta, rejection/resubmission, role checks, duplicate posting, failed-save and approval rollback, tab conflict, corrupt-record protection, OCR ambiguity, cache isolation and shell assets");
